spring:
  security:
    user:
      name: jyoti
      password: jyoti
  application:
    name: student
  datasource:
    #initialization-mode: always
    generate-unique-name: false
    url: jdbc:h2:mem:mystudentdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      platform: h2
server:
  port: 8090

